version: '3.8'
volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/usra/dataa/wordpress

  mariadb:
    name : mariadb
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /home/usra/dataa/mariadb

networks:
  Inception_network:
    name: Inception_network


services:

  ngnix:
    depends_on:
      - wordpress
    container_name : ngnix
    build : requirements/nginx
    image : ngnix
    ports:
      - 443:443
    restart: on-failure
    env_file: .env
    networks:
      - Inception_network
    volumes :
      - wordpress:/var/www/html

  wordpress:
    container_name : wordpress
    build : requirements/wordpress
    image : wordpress
    restart: on-failure
    env_file: .env
    networks:
      - Inception_network
    volumes :
      - wordpress:/var/www/html
  
  mariadb :
    container_name : mariadb
    build: requirements/mariadb
    image : mariadb
    restart: on-failure
    env_file: .env
    networks:
      - Inception_network
    volumes:
      - mariadb:/var/lib/mysql
